<?
$PERM["dashboard"]["11"]="D";
$PERM["dashboard"]["49"]="R";
$PERM["toolz"]["1"]="R";
$PERM["video"]["*"]="R";
$PERM["apps"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["limit"]["13"]="R";
$PERM["upload"]["17"]="R";
$PERM["upload"]["13"]="R";
$PERM["pub"]["17"]="R";
$PERM["pub"]["*"]="R";
$PERM["extranet"]["G13"]="R";
$PERM["extranet"]["G11"]="R";
$PERM["/"]["*"]="D";
$PERM["/"]["2"]="D";
$PERM["/"]["1"]="R";
$PERM["/"]["11"]="R";
$PERM["rest"]["2"]="R";
$PERM["oauth"]["2"]="R";
$PERM["mobileapp"]["13"]="R";
?>